### ISSUE TITLE
Motor Control Dashboard

### ISSUE THREAD

**Issue by ivanchenoweth** [ivanchenoweth/poc-dashboard-iot#3]
## Motor Control Dashboard

> We need to create a User GUI (mockup), to interact with the relevant process.  This is in order to have a process for the operational user.

* Location: http://localhost/process  (Web app only) 

### Acceptance criteria (PO)
1. We need interact with the GUI recording each activity in the log table database, that is displayed in the "logs" adminiatrator option.

## BDD: 

* Scenario 1: An User is Logged: 
* **Given:** The "Log in" Button is clicked and the User role is identified
* **Then:** The GUI (mockup) has to be displayed. 

## TASKS  
> At least these task splitting have to be included:
- [ ] Create for view
- [ ] Create the controller
- [ ] Create the Service (if apply)
- [ ] Create unit test 
- [ ] Create automated or/and functional tests
- [ ] Code review Dev 1
- [ ] Code review Dev 2
- [ ] Profiling (web app only)

## Mockup: **Logs**
![Process_CRUD_login](/uploads/6334a65c1f4075a423916d6687e74bd9/Process_CRUD_login.png)
